THEMES = (
    ("light", "Light"),
    ("dark", "Dark"),
    ("cupcake", "Cupcake"),
    ("bumblebee", "Bumblebee"),
    ("emerald", "Emerald"),
    ("corporate", "Corporate"),
    ("synthwave", "Synthwave"),
    ("retro", "Retro"),
    ("cyberpunk", "Cyberpunk"),
    ("valentine", "Valentine"),
    ("halloween", "Halloween"),
    ("garden", "Garden"),
    ("forest", "Forest"),
    ("aqua", "Aqua"),
    ("lofi", "Lo-Fi"),
    ("pastel", "Pastel"),
    ("fantasy", "Fantasy"),
    ("wireframe", "Wireframe"),
    ("black", "Black"),
    ("luxury", "Luxury"),
    ("dracula", "Dracula"),
    ("cmyk", "CMYK"),
    ("autumn", "Autumn"),
    ("business", "Business"),
    ("acid", "Acid"),
    ("lemonade", "Lemonade"),
    ("night", "Night"),
    ("coffee", "Coffee"),
    ("winter", "Winter"),
    ("dim", "Dim"),
    ("nord", "Nord"),
    ("sunset", "Sunset"),
    ("caramellatte", "Caramellatte"),
    ("abyss", "Abyss"),
    ("silk", "Silk"),
)


def ThemeChoices() -> list[dict[str, str]]:
    return [{"name": name, "label": label} for name, label in THEMES]
